// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Order.Infrastructure;

#nullable disable

namespace Order.Infrastructure.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20251125132529_AddOrderNumber")]
    partial class AddOrderNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("order")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Order.Domain.DeliveryAggregate.DeliveryMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMethods", "order");
                });

            modelBuilder.Entity("Order.Domain.DeliveryAggregate.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeliveryMethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryMethodId");

                    b.ToTable("Cities", "order");
                });

            modelBuilder.Entity("Order.Domain.DeliveryAggregate.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<long>("HouseNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Departments", "order");
                });

            modelBuilder.Entity("Order.Domain.DeliveryAggregate.Entities.PostMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<long>("HouseNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PostMachines", "order");
                });

            modelBuilder.Entity("Order.Domain.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", "order");
                });

            modelBuilder.Entity("Order.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryMethodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentOption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UsedBonusesAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<bool>("WithBonuses")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Orders", "order");
                });

            modelBuilder.Entity("Order.Domain.DeliveryAggregate.Entities.City", b =>
                {
                    b.HasOne("Order.Domain.DeliveryAggregate.DeliveryMethod", "DeliveryMethod")
                        .WithMany("_cities")
                        .HasForeignKey("DeliveryMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryMethod");
                });

            modelBuilder.Entity("Order.Domain.DeliveryAggregate.Entities.Department", b =>
                {
                    b.HasOne("Order.Domain.DeliveryAggregate.Entities.City", "City")
                        .WithMany("_departments")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Order.Domain.DeliveryAggregate.Entities.PostMachine", b =>
                {
                    b.HasOne("Order.Domain.DeliveryAggregate.Entities.City", "City")
                        .WithMany("_postMachines")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Order.Domain.OrderAggregate.Entities.OrderItem", b =>
                {
                    b.HasOne("Order.Domain.OrderAggregate.Order", "Order")
                        .WithMany("_orderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Order.Domain.OrderAggregate.Order", b =>
                {
                    b.OwnsOne("Order.Domain.OrderAggregate.ValueObjects.CustomerInfo", "CustomerInfo", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Shared.Domain.ValueObjects.FullName", "FullName", b2 =>
                                {
                                    b2.Property<Guid>("CustomerInfoOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Customer_FirstName");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Customer_LastName");

                                    b2.Property<string>("MiddleName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Customer_MiddleName");

                                    b2.HasKey("CustomerInfoOrderId");

                                    b2.ToTable("Orders", "order");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerInfoOrderId");
                                });

                            b1.OwnsOne("Shared.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b2 =>
                                {
                                    b2.Property<Guid>("CustomerInfoOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Customer_PhoneNumber");

                                    b2.HasKey("CustomerInfoOrderId");

                                    b2.ToTable("Orders", "order");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerInfoOrderId");
                                });

                            b1.OwnsOne("Order.Domain.OrderAggregate.ValueObjects.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("CustomerInfoOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Customer_Email");

                                    b2.HasKey("CustomerInfoOrderId");

                                    b2.ToTable("Orders", "order");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerInfoOrderId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("FullName")
                                .IsRequired();

                            b1.Navigation("PhoneNumber")
                                .IsRequired();
                        });

                    b.OwnsOne("Order.Domain.OrderAggregate.ValueObjects.DeliveryInfo", "DeliveryInfo", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DeliveryCity");

                            b1.Property<long>("HouseNumber")
                                .HasColumnType("bigint")
                                .HasColumnName("DeliveryHouseNumber");

                            b1.Property<long?>("Number")
                                .HasColumnType("bigint")
                                .HasColumnName("DeliveryNumber");

                            b1.Property<string>("Option")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DeliveryOption");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DeliveryStreet");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Order.Domain.OrderAggregate.ValueObjects.RecipientInfo", "RecipientInfo", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Shared.Domain.ValueObjects.FullName", "FullName", b2 =>
                                {
                                    b2.Property<Guid>("RecipientInfoOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Recipient_FirstName");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Recipient_LastName");

                                    b2.Property<string>("MiddleName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Recipient_MiddleName");

                                    b2.HasKey("RecipientInfoOrderId");

                                    b2.ToTable("Orders", "order");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipientInfoOrderId");
                                });

                            b1.OwnsOne("Shared.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b2 =>
                                {
                                    b2.Property<Guid>("RecipientInfoOrderId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Recipient_PhoneNumber");

                                    b2.HasKey("RecipientInfoOrderId");

                                    b2.ToTable("Orders", "order");

                                    b2.WithOwner()
                                        .HasForeignKey("RecipientInfoOrderId");
                                });

                            b1.Navigation("FullName")
                                .IsRequired();

                            b1.Navigation("PhoneNumber")
                                .IsRequired();
                        });

                    b.Navigation("CustomerInfo")
                        .IsRequired();

                    b.Navigation("DeliveryInfo")
                        .IsRequired();

                    b.Navigation("RecipientInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Order.Domain.DeliveryAggregate.DeliveryMethod", b =>
                {
                    b.Navigation("_cities");
                });

            modelBuilder.Entity("Order.Domain.DeliveryAggregate.Entities.City", b =>
                {
                    b.Navigation("_departments");

                    b.Navigation("_postMachines");
                });

            modelBuilder.Entity("Order.Domain.OrderAggregate.Order", b =>
                {
                    b.Navigation("_orderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
