// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wolfix.Infrastructure;

#nullable disable

namespace Wolfix.Infrastructure.Migrations
{
    [DbContext(typeof(WolfixStoreContext))]
    [Migration("20250725124032_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wolfix.Domain.Shared.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.CategoryAggregate.Category", b =>
                {
                    b.HasBaseType("Wolfix.Domain.Shared.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.CategoryAggregate.Entities.ProductAttribute", b =>
                {
                    b.HasBaseType("Wolfix.Domain.Shared.BaseEntity");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductAttributes", (string)null);
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.CategoryAggregate.Entities.ProductVariant", b =>
                {
                    b.HasBaseType("Wolfix.Domain.Shared.BaseEntity");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductVariants", (string)null);
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Entities.Discount", b =>
                {
                    b.HasBaseType("Wolfix.Domain.Shared.BaseEntity");

                    b.Property<DateTime>("ExpirationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Percent")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Discounts", (string)null);
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Entities.ProductAttributeValue", b =>
                {
                    b.HasBaseType("Wolfix.Domain.Shared.BaseEntity");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributeValues", (string)null);
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Entities.ProductVariantValue", b =>
                {
                    b.HasBaseType("Wolfix.Domain.Shared.BaseEntity");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariantValues", (string)null);
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Entities.Review", b =>
                {
                    b.HasBaseType("Wolfix.Domain.Shared.BaseEntity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Product", b =>
                {
                    b.HasBaseType("Wolfix.Domain.Shared.BaseEntity");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Wolfix.Domain.Shared.BlobResource", b =>
                {
                    b.HasBaseType("Wolfix.Domain.Shared.BaseEntity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("EntityId");

                    b.HasIndex("ProductId");

                    b.ToTable("BlobResource");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.CategoryAggregate.Category", b =>
                {
                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Wolfix.Domain.Catalog.CategoryAggregate.Category", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Catalog.CategoryAggregate.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.CategoryAggregate.Entities.ProductAttribute", b =>
                {
                    b.HasOne("Wolfix.Domain.Catalog.CategoryAggregate.Category", "Category")
                        .WithMany("_productAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Wolfix.Domain.Catalog.CategoryAggregate.Entities.ProductAttribute", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.CategoryAggregate.Entities.ProductVariant", b =>
                {
                    b.HasOne("Wolfix.Domain.Catalog.CategoryAggregate.Category", "Category")
                        .WithMany("_productVariants")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Wolfix.Domain.Catalog.CategoryAggregate.Entities.ProductVariant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Entities.Discount", b =>
                {
                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Wolfix.Domain.Catalog.ProductAggregate.Entities.Discount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Catalog.ProductAggregate.Product", null)
                        .WithOne("Discount")
                        .HasForeignKey("Wolfix.Domain.Catalog.ProductAggregate.Entities.Discount", "ProductId");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Entities.ProductAttributeValue", b =>
                {
                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Wolfix.Domain.Catalog.ProductAggregate.Entities.ProductAttributeValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Catalog.ProductAggregate.Product", "Product")
                        .WithMany("_productsAttributeValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Entities.ProductVariantValue", b =>
                {
                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Wolfix.Domain.Catalog.ProductAggregate.Entities.ProductVariantValue", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Catalog.ProductAggregate.Product", "Product")
                        .WithMany("_productVariantValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Entities.Review", b =>
                {
                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Wolfix.Domain.Catalog.ProductAggregate.Entities.Review", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Catalog.ProductAggregate.Product", "Product")
                        .WithMany("_reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Product", b =>
                {
                    b.HasOne("Wolfix.Domain.Catalog.CategoryAggregate.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Wolfix.Domain.Catalog.ProductAggregate.Product", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wolfix.Domain.Shared.BlobResource", b =>
                {
                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Shared.BaseEntity", null)
                        .WithOne()
                        .HasForeignKey("Wolfix.Domain.Shared.BlobResource", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfix.Domain.Catalog.ProductAggregate.Product", null)
                        .WithMany("Resources")
                        .HasForeignKey("ProductId");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.CategoryAggregate.Category", b =>
                {
                    b.Navigation("_productAttributes");

                    b.Navigation("_productVariants");
                });

            modelBuilder.Entity("Wolfix.Domain.Catalog.ProductAggregate.Product", b =>
                {
                    b.Navigation("Discount");

                    b.Navigation("Resources");

                    b.Navigation("_productVariantValues");

                    b.Navigation("_productsAttributeValues");

                    b.Navigation("_reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
