// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Support.Infrastructure;

#nullable disable

namespace Support.Infrastructure.Migrations
{
    [DbContext(typeof(SupportContext))]
    [Migration("20251210214551_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("support")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Support.Domain.Entities.Support", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Supports", "support");
                });

            modelBuilder.Entity("Support.Domain.Entities.SupportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseContent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<Guid?>("SupportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SupportId");

                    b.ToTable("SupportRequests", "support");
                });

            modelBuilder.Entity("Support.Domain.Entities.Support", b =>
                {
                    b.OwnsOne("Shared.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("SupportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MiddleName");

                            b1.HasKey("SupportId");

                            b1.ToTable("Supports", "support");

                            b1.WithOwner()
                                .HasForeignKey("SupportId");
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("Support.Domain.Entities.SupportRequest", b =>
                {
                    b.HasOne("Support.Domain.Entities.Support", "ProcessedBy")
                        .WithMany("SupportRequests")
                        .HasForeignKey("SupportId");

                    b.OwnsOne("Shared.Domain.ValueObjects.BirthDate", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("SupportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("BirthDate");

                            b1.HasKey("SupportRequestId");

                            b1.ToTable("SupportRequests", "support");

                            b1.WithOwner()
                                .HasForeignKey("SupportRequestId");
                        });

                    b.OwnsOne("Shared.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("SupportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("SupportRequestId");

                            b1.ToTable("SupportRequests", "support");

                            b1.WithOwner()
                                .HasForeignKey("SupportRequestId");
                        });

                    b.OwnsOne("Shared.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("SupportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("SupportRequestId");

                            b1.ToTable("SupportRequests", "support");

                            b1.WithOwner()
                                .HasForeignKey("SupportRequestId");
                        });

                    b.OwnsOne("Shared.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("SupportRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MiddleName");

                            b1.HasKey("SupportRequestId");

                            b1.ToTable("SupportRequests", "support");

                            b1.WithOwner()
                                .HasForeignKey("SupportRequestId");
                        });

                    b.Navigation("BirthDate")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("ProcessedBy");
                });

            modelBuilder.Entity("Support.Domain.Entities.Support", b =>
                {
                    b.Navigation("SupportRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
